apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vwt8kaphj-python 
  janus-idp.io/tekton: vwt8kaphj-python
  backstage.io/kubernetes-id: vwt8kaphj-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vwt8kaphj-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml