apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vwt8kaphj-python
  janus-idp.io/tekton: vwt8kaphj-python
  backstage.io/kubernetes-id: vwt8kaphj-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vwt8kaphj-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
